server:
  port: 8090

spring:
  collector:
    kafka:
      telemetry:
        bootstrap:
          servers: "localhost:9092"
        sensor:
          topic: "telemetry.sensors.v1"
        snapshot:
          topic: "telemetry.snapshots.v1"
