spring:
  cloud:
    config:
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
  application:
    name: aggregator
  config:
    import: configserver:http://localhost:8888