resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
  instances:
    warehouseFeignClient:
      ignore-exceptions:
        - ru.practicum.feign.warehouse.exception.WarehouseNotFoundException
        - ru.practicum.feign.warehouse.exception.WarehouseBadRequestException
      slidingWindowSize: 10
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true